publisher:
  name: Tarbh
  address: 8XCMUz7sShehraptZymbQZ3fBJ8fvHdhLqu8VtWigmQt
  website: https://tarbh.net/
  email: admin@tarbh.net
  media:
    - purpose: icon
      uri: ./media/tarbh.png
app:
  name: Warp
  address: FnfBHDj79peFsWhbMvMEsJQ8KCrFKztRTAh6KD51uwVh
  android_package: net.tarbh.warp
  urls:
    license_url: https://github.com/ronanyeah/warp/blob/master/publishing/policies/LICENSE
    copyright_url: https://github.com/ronanyeah/warp/blob/master/publishing/policies/LICENSE
    privacy_policy_url: https://github.com/ronanyeah/warp/blob/master/publishing/policies/PRIVACY.md
    website: https://tarbh.net/
  media:
    - purpose: icon
      uri: ./media/warp.png
release:
  address: 2cmCMydsvZFqjJ4mMyecRbobgkQbmJXEYkzKQcgRnR61
  media:
    - purpose: icon
      uri: ./media/warp.png
    - purpose: screenshot
      uri: ./media/screenshots/1.png
    - purpose: screenshot
      uri: ./media/screenshots/2.png
    - purpose: screenshot
      uri: ./media/screenshots/3.png
    - purpose: screenshot
      uri: ./media/screenshots/4.png
  files:
    - purpose: install
      uri: ../android/app/release/app-release.apk
  catalog:
    en-US:
      name: Warp
      short_description: Multichain Seed Vault access.
      long_description: Unlock multichain Seed Vault experiences using Warp.
      new_in_version: Get started with Warp.
      saga_features: Utilise the Saga Seed Vault in new ways.
solana_mobile_dapp_publisher_portal:
  testing_instructions: 'Interact with Warp using any Seed Vault enabled device. Code: https://github.com/ronanyeah/warp'
lastSubmittedVersionOnChain:
  address: 2cmCMydsvZFqjJ4mMyecRbobgkQbmJXEYkzKQcgRnR61
  version_code: 2
  apk_hash: iVwobSpKn22KTHxVI5avGbQyM36LdOQNegy4+iQTQhc=
lastUpdatedVersionOnStore:
  address: 2cmCMydsvZFqjJ4mMyecRbobgkQbmJXEYkzKQcgRnR61
